// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import '../models/entities/contenitore_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 5360143009456191875),
    name: 'ContenitoreEntity',
    lastPropertyId: const obx_int.IdUid(8, 1941727811085977414),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6898863564306452794),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4727854869268610133),
        name: 'nome',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 40113786888073383),
        name: 'pesoContenitore',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3363097790761066075),
        name: 'pesoCibo',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5095424138460331555),
        name: 'porzioni',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4249502453417767260),
        name: 'pesoPorzione',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 1941727811085977414),
        name: 'dataCaricamento',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 5360143009456191875),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [3920905685616008095],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    ContenitoreEntity: obx_int.EntityDefinition<ContenitoreEntity>(
      model: _entities[0],
      toOneRelations: (ContenitoreEntity object) => [],
      toManyRelations: (ContenitoreEntity object) => {},
      getId: (ContenitoreEntity object) => object.id,
      setId: (ContenitoreEntity object, int id) {
        object.id = id;
      },
      objectToFB: (ContenitoreEntity object, fb.Builder fbb) {
        final nomeOffset = object.nome == null
            ? null
            : fbb.writeString(object.nome!);
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nomeOffset);
        fbb.addFloat64(2, object.pesoContenitore);
        fbb.addFloat64(3, object.pesoCibo);
        fbb.addInt64(4, object.porzioni);
        fbb.addFloat64(5, object.pesoPorzione);
        fbb.addInt64(7, object.dataCaricamento?.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final dataCaricamentoValue = const fb.Int64Reader().vTableGetNullable(
          buffer,
          rootOffset,
          18,
        );
        final object = ContenitoreEntity()
          ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..nome = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 6)
          ..pesoContenitore = const fb.Float64Reader().vTableGetNullable(
            buffer,
            rootOffset,
            8,
          )
          ..pesoCibo = const fb.Float64Reader().vTableGetNullable(
            buffer,
            rootOffset,
            10,
          )
          ..porzioni = const fb.Int64Reader().vTableGetNullable(
            buffer,
            rootOffset,
            12,
          )
          ..pesoPorzione = const fb.Float64Reader().vTableGetNullable(
            buffer,
            rootOffset,
            14,
          )
          ..dataCaricamento = dataCaricamentoValue == null
              ? null
              : DateTime.fromMillisecondsSinceEpoch(dataCaricamentoValue);

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [ContenitoreEntity] entity fields to define ObjectBox queries.
class ContenitoreEntity_ {
  /// See [ContenitoreEntity.id].
  static final id = obx.QueryIntegerProperty<ContenitoreEntity>(
    _entities[0].properties[0],
  );

  /// See [ContenitoreEntity.nome].
  static final nome = obx.QueryStringProperty<ContenitoreEntity>(
    _entities[0].properties[1],
  );

  /// See [ContenitoreEntity.pesoContenitore].
  static final pesoContenitore = obx.QueryDoubleProperty<ContenitoreEntity>(
    _entities[0].properties[2],
  );

  /// See [ContenitoreEntity.pesoCibo].
  static final pesoCibo = obx.QueryDoubleProperty<ContenitoreEntity>(
    _entities[0].properties[3],
  );

  /// See [ContenitoreEntity.porzioni].
  static final porzioni = obx.QueryIntegerProperty<ContenitoreEntity>(
    _entities[0].properties[4],
  );

  /// See [ContenitoreEntity.pesoPorzione].
  static final pesoPorzione = obx.QueryDoubleProperty<ContenitoreEntity>(
    _entities[0].properties[5],
  );

  /// See [ContenitoreEntity.dataCaricamento].
  static final dataCaricamento = obx.QueryDateProperty<ContenitoreEntity>(
    _entities[0].properties[6],
  );
}
